export const network_subset = {
  "nodes": [
    { "id": 1, "name": "20min.ch", "count": 20 },
    { "id": 2, "name": "adnxs.com", "count": 1 },
    { "id": 3, "name": "adsafeprotected.com", "count": 1 },
    { "id": 4, "name": "cookielaw.org", "count": 1 },
    { "id": 5, "name": "da-services.ch", "count": 1 },
    { "id": 6, "name": "doubleclick.net", "count": 1 },
    { "id": 7, "name": "facebook.com", "count": 1 },
    { "id": 8, "name": "facebook.net", "count": 1 },
    { "id": 9, "name": "fooby.ch", "count": 1 },
    { "id": 10, "name": "google-analytics.com", "count": 1 },
    { "id": 11, "name": "google.ch", "count": 1 },
    { "id": 12, "name": "google.com", "count": 1 },
    { "id": 13, "name": "googletagmanager.com", "count": 1 },
    { "id": 14, "name": "mpod.ch", "count": 1 },
    { "id": 15, "name": "onetrust.com", "count": 1 },
    { "id": 16, "name": "opecloud.com", "count": 1 },
    { "id": 17, "name": "scorecardresearch.com", "count": 1 },
    { "id": 18, "name": "tamedia.link", "count": 1 },
    { "id": 19, "name": "tda.link", "count": 1 },
    { "id": 20, "name": "tiktok.com", "count": 1 },
    { "id": 21, "name": "unitycms.io", "count": 1 },
    { "id": 22, "name": "", "count": 1 },
    { "id": 23, "count": 1 }
  ],
  "links": [
    { "source": 2, "target": 1 },
    { "source": 3, "target": 1 },
    { "source": 4, "target": 1 },
    { "source": 5, "target": 1 },
    { "source": 6, "target": 1 },
    { "source": 7, "target": 1 },
    { "source": 8, "target": 1 },
    { "source": 9, "target": 1 },
    { "source": 10, "target": 1 },
    { "source": 11, "target": 1 },
    { "source": 12, "target": 1 },
    { "source": 13, "target": 1 },
    { "source": 14, "target": 1 },
    { "source": 15, "target": 1 },
    { "source": 16, "target": 1 },
    { "source": 17, "target": 1 },
    { "source": 18, "target": 1 },
    { "source": 19, "target": 1 },
    { "source": 20, "target": 1 },
    { "source": 21, "target": 1 },
    { "source": 23, "target": 22 }
  ]
}
