import { Domain } from './interfaces';

export const DOMAINS: Domain[] = [
  {
    name: '20min.ch',
    thirdParties: [
      {
        requestDomain: 'acuityplatform.com',
        owner: 'AcuityAds',
        ownerCountry: 'CA',
      },
      { requestDomain: 'ad4m.at', owner: '', ownerCountry: '' },
      { requestDomain: 'adentifi.com', owner: '', ownerCountry: '' },
      { requestDomain: 'adnxs.com', owner: 'Xandr', ownerCountry: 'US' },
      {
        requestDomain: 'adsafeprotected.com',
        owner: 'Integral Ad Science',
        ownerCountry: 'US',
      },
      {
        requestDomain: 'adsrvr.org',
        owner: 'The Trade Desk',
        ownerCountry: 'US',
      },
      { requestDomain: 'advangelists.com', owner: '', ownerCountry: '' },
      {
        requestDomain: 'amazon-adsystem.com',
        owner: 'Amazon Marketing Services',
        ownerCountry: 'US',
      },
      {
        requestDomain: 'casalemedia.com',
        owner: 'Index Exchange',
        ownerCountry: 'CA',
      },
      { requestDomain: 'cookielaw.org', owner: '', ownerCountry: '' },
      { requestDomain: 'da-services.ch', owner: '', ownerCountry: '' },
      {
        requestDomain: 'doubleclick.net',
        owner: 'DoubleClick',
        ownerCountry: 'US',
      },
      { requestDomain: 'facebook.com', owner: 'Facebook', ownerCountry: 'US' },
      { requestDomain: 'facebook.net', owner: 'Facebook', ownerCountry: 'US' },
      { requestDomain: 'fooby.ch', owner: '', ownerCountry: '' },
      {
        requestDomain: 'google-analytics.com',
        owner: 'Google Analytics',
        ownerCountry: 'US',
      },
      { requestDomain: 'google.ch', owner: 'Google', ownerCountry: 'US' },
      { requestDomain: 'google.com', owner: 'Google', ownerCountry: 'US' },
      {
        requestDomain: 'googletagmanager.com',
        owner: 'Google Tag Manager',
        ownerCountry: 'US',
      },
      {
        requestDomain: 'indexww.com',
        owner: 'Index Exchange',
        ownerCountry: 'CA',
      },
      { requestDomain: 'mathtag.com', owner: 'Media Math', ownerCountry: 'US' },
      { requestDomain: 'onetrust.com', owner: '', ownerCountry: '' },
      { requestDomain: 'opecloud.com', owner: '', ownerCountry: '' },
      {
        requestDomain: 'quantserve.com',
        owner: 'Quantcast',
        ownerCountry: 'US',
      },
      {
        requestDomain: 'scorecardresearch.com',
        owner: 'ScorecardResearch',
        ownerCountry: 'US',
      },
      {
        requestDomain: 'stickyadstv.com',
        owner: 'StickyADS.tv',
        ownerCountry: 'US',
      },
      { requestDomain: 'tamedia.link', owner: '', ownerCountry: '' },
      { requestDomain: 'tda.link', owner: '', ownerCountry: '' },
      { requestDomain: 'tiktok.com', owner: '', ownerCountry: '' },
      { requestDomain: 'unitycms.io', owner: '', ownerCountry: '' },
    ],
  },
  {
    name: 'blick.ch',
    thirdParties: [
      { requestDomain: 'admeira.ch', owner: '', ownerCountry: '' },
      { requestDomain: 'adnxs-simple.com', owner: '', ownerCountry: '' },
      { requestDomain: 'adnxs.com', owner: 'Xandr', ownerCountry: 'US' },
      {
        requestDomain: 'adsafeprotected.com',
        owner: 'Integral Ad Science',
        ownerCountry: 'US',
      },
      { requestDomain: 'blickdeal.ch', owner: '', ownerCountry: '' },
      { requestDomain: 'boltdns.net', owner: '', ownerCountry: '' },
      { requestDomain: 'brandmetrics.com', owner: '', ownerCountry: '' },
      {
        requestDomain: 'brightcove.com',
        owner: 'Brightcove',
        ownerCountry: 'US',
      },
      {
        requestDomain: 'brightcove.net',
        owner: 'Brightcove',
        ownerCountry: 'US',
      },
      { requestDomain: 'cwi.re', owner: '', ownerCountry: '' },
      { requestDomain: 'cxense.com', owner: 'Cxense', ownerCountry: 'NO' },
      {
        requestDomain: 'doubleclick.net',
        owner: 'DoubleClick',
        ownerCountry: 'US',
      },
      { requestDomain: 'dreamlab.pl', owner: '', ownerCountry: '' },
      { requestDomain: 'facebook.com', owner: 'Facebook', ownerCountry: 'US' },
      { requestDomain: 'facebook.net', owner: 'Facebook', ownerCountry: 'US' },
      {
        requestDomain: 'google-analytics.com',
        owner: 'Google Analytics',
        ownerCountry: 'US',
      },
      { requestDomain: 'google.ch', owner: 'Google', ownerCountry: 'US' },
      { requestDomain: 'google.com', owner: 'Google', ownerCountry: 'US' },
      {
        requestDomain: 'googletagmanager.com',
        owner: 'Google Tag Manager',
        ownerCountry: 'US',
      },
      { requestDomain: 'h-cdn.com', owner: '', ownerCountry: '' },
      { requestDomain: 'npttech.com', owner: '', ownerCountry: '' },
      { requestDomain: 'ocdn.eu', owner: '', ownerCountry: '' },
      { requestDomain: 'onesignal.com', owner: '', ownerCountry: '' },
      { requestDomain: 'onet.pl', owner: '', ownerCountry: '' },
      { requestDomain: 'opecloud.com', owner: '', ownerCountry: '' },
      { requestDomain: 'piano.io', owner: '', ownerCountry: '' },
      { requestDomain: 'realtimely.io', owner: '', ownerCountry: '' },
      {
        requestDomain: 'scorecardresearch.com',
        owner: 'ScorecardResearch',
        ownerCountry: 'US',
      },
      { requestDomain: 'sentry.io', owner: '', ownerCountry: '' },
      { requestDomain: 'tinypass.com', owner: '', ownerCountry: '' },
    ],
  },
  {
    name: 'derbund.ch',
    thirdParties: [
      { requestDomain: 'ad4m.at', owner: '', ownerCountry: '' },
      { requestDomain: 'adform.net', owner: 'AdForm', ownerCountry: 'DK' },
      { requestDomain: 'adnxs-simple.com', owner: '', ownerCountry: '' },
      { requestDomain: 'adnxs.com', owner: 'Xandr', ownerCountry: 'US' },
      {
        requestDomain: 'ads-twitter.com',
        owner: 'Twitter',
        ownerCountry: 'US',
      },
      {
        requestDomain: 'adsafeprotected.com',
        owner: 'Integral Ad Science',
        ownerCountry: 'US',
      },
      {
        requestDomain: 'adsrvr.org',
        owner: 'The Trade Desk',
        ownerCountry: 'US',
      },
      {
        requestDomain: 'amazon-adsystem.com',
        owner: 'Amazon Marketing Services',
        ownerCountry: 'US',
      },
      {
        requestDomain: 'casalemedia.com',
        owner: 'Index Exchange',
        ownerCountry: 'CA',
      },
      {
        requestDomain: 'cloudflare.com',
        owner: 'Cloudflare',
        ownerCountry: 'US',
      },
      { requestDomain: 'cxense.com', owner: 'Cxense', ownerCountry: 'NO' },
      { requestDomain: 'da-services.ch', owner: '', ownerCountry: '' },
      {
        requestDomain: 'demdex.net',
        owner: 'Adobe Audience Manager',
        ownerCountry: 'US',
      },
      {
        requestDomain: 'doubleclick.net',
        owner: 'DoubleClick',
        ownerCountry: 'US',
      },
      { requestDomain: 'facebook.com', owner: 'Facebook', ownerCountry: 'US' },
      { requestDomain: 'facebook.net', owner: 'Facebook', ownerCountry: 'US' },
      {
        requestDomain: 'google-analytics.com',
        owner: 'Google Analytics',
        ownerCountry: 'US',
      },
      { requestDomain: 'google.ch', owner: 'Google', ownerCountry: 'US' },
      { requestDomain: 'google.com', owner: 'Google', ownerCountry: 'US' },
      {
        requestDomain: 'googleadservices.com',
        owner: 'AdSense',
        ownerCountry: 'US',
      },
      {
        requestDomain: 'googleapis.com',
        owner: 'Google APIs',
        ownerCountry: 'US',
      },
      {
        requestDomain: 'googlesyndication.com',
        owner: 'AdSense',
        ownerCountry: 'US',
      },
      {
        requestDomain: 'googletagmanager.com',
        owner: 'Google Tag Manager',
        ownerCountry: 'US',
      },
      {
        requestDomain: 'googletagservices.com',
        owner: 'Google Tag Manager',
        ownerCountry: 'US',
      },
      { requestDomain: 'gstatic.com', owner: 'Google', ownerCountry: 'US' },
      {
        requestDomain: 'indexww.com',
        owner: 'Index Exchange',
        ownerCountry: 'CA',
      },
      {
        requestDomain: 'myvisualiq.net',
        owner: 'Nielsen Online',
        ownerCountry: 'US',
      },
      { requestDomain: 'opecloud.com', owner: '', ownerCountry: '' },
      { requestDomain: 'owneriq.net', owner: 'OwnerIQ', ownerCountry: 'US' },
      { requestDomain: 'parsely.com', owner: 'Parsely', ownerCountry: 'US' },
      { requestDomain: 'piano.io', owner: '', ownerCountry: '' },
      { requestDomain: 'sc-static.net', owner: '', ownerCountry: '' },
      {
        requestDomain: 'scorecardresearch.com',
        owner: 'ScorecardResearch',
        ownerCountry: 'US',
      },
      { requestDomain: 't.co', owner: 'Twitter', ownerCountry: 'US' },
      { requestDomain: 'tamedia.ch', owner: '', ownerCountry: '' },
      { requestDomain: 'tamedia.link', owner: '', ownerCountry: '' },
      { requestDomain: 'tda.link', owner: '', ownerCountry: '' },
      { requestDomain: 'tiktok.com', owner: '', ownerCountry: '' },
      { requestDomain: 'tinypass.com', owner: '', ownerCountry: '' },
      { requestDomain: 'twitter.com', owner: 'Twitter', ownerCountry: 'US' },
      { requestDomain: 'tx.group', owner: '', ownerCountry: '' },
      { requestDomain: 'unitycms.io', owner: '', ownerCountry: '' },
    ],
  },
  {
    name: 'nzz.ch',
    thirdParties: [
      { requestDomain: 'adform.net', owner: 'AdForm', ownerCountry: 'DK' },
      {
        requestDomain: 'adition.com',
        owner: 'Adition Technologies',
        ownerCountry: 'DE',
      },
      { requestDomain: 'adnxs.com', owner: 'Xandr', ownerCountry: 'US' },
      { requestDomain: 'adnz.co', owner: '', ownerCountry: '' },
      {
        requestDomain: 'ads-twitter.com',
        owner: 'Twitter',
        ownerCountry: 'US',
      },
      { requestDomain: 'adtech.de', owner: 'ONE by Aol', ownerCountry: 'US' },
      { requestDomain: 'astatic.org', owner: '', ownerCountry: '' },
      {
        requestDomain: 'chartbeat.com',
        owner: 'Chartbeat',
        ownerCountry: 'US',
      },
      {
        requestDomain: 'chartbeat.net',
        owner: 'Chartbeat',
        ownerCountry: 'US',
      },
      {
        requestDomain: 'consensu.org',
        owner: 'IAB Europe',
        ownerCountry: 'BE',
      },
      { requestDomain: 'danzz.ch', owner: '', ownerCountry: '' },
      {
        requestDomain: 'demdex.net',
        owner: 'Adobe Audience Manager',
        ownerCountry: 'US',
      },
      {
        requestDomain: 'doubleclick.net',
        owner: 'DoubleClick',
        ownerCountry: 'US',
      },
      {
        requestDomain: 'everesttech.net',
        owner: 'Adobe Experience Cloud',
        ownerCountry: 'US',
      },
      { requestDomain: 'facebook.com', owner: 'Facebook', ownerCountry: 'US' },
      { requestDomain: 'facebook.net', owner: 'Facebook', ownerCountry: 'US' },
      { requestDomain: 'google.com', owner: 'Google', ownerCountry: 'US' },
      {
        requestDomain: 'googleadservices.com',
        owner: 'AdSense',
        ownerCountry: 'US',
      },
      { requestDomain: 'hotjar.com', owner: 'Hotjar', ownerCountry: 'MT' },
      { requestDomain: 'hotjar.io', owner: 'Hotjar', ownerCountry: 'MT' },
      { requestDomain: 'licdn.com', owner: 'LinkedIn', ownerCountry: 'US' },
      { requestDomain: 'linkedin.com', owner: 'LinkedIn', ownerCountry: 'US' },
      {
        requestDomain: 'omtrdc.net',
        owner: 'Adobe Experience Cloud',
        ownerCountry: 'US',
      },
      {
        requestDomain: 'scorecardresearch.com',
        owner: 'ScorecardResearch',
        ownerCountry: 'US',
      },
      { requestDomain: 'static-nzz.ch', owner: '', ownerCountry: '' },
      { requestDomain: 't.co', owner: 'Twitter', ownerCountry: 'US' },
      { requestDomain: 'themarket.ch', owner: '', ownerCountry: '' },
      { requestDomain: 'twitter.com', owner: 'Twitter', ownerCountry: 'US' },
    ],
  },
  {
    name: 'watson.ch',
    thirdParties: [
      { requestDomain: 'adform.net', owner: 'AdForm', ownerCountry: 'DK' },
      { requestDomain: 'adnxs.com', owner: 'Xandr', ownerCountry: 'US' },
      { requestDomain: 'adnz.co', owner: '', ownerCountry: '' },
      {
        requestDomain: 'adsafeprotected.com',
        owner: 'Integral Ad Science',
        ownerCountry: 'US',
      },
      {
        requestDomain: 'adsrvr.org',
        owner: 'The Trade Desk',
        ownerCountry: 'US',
      },
      {
        requestDomain: 'chartbeat.com',
        owner: 'Chartbeat',
        ownerCountry: 'US',
      },
      {
        requestDomain: 'cloudflare.com',
        owner: 'Cloudflare',
        ownerCountry: 'US',
      },
      { requestDomain: 'codevelop.network', owner: '', ownerCountry: '' },
      { requestDomain: 'criteo.com', owner: 'Criteo', ownerCountry: 'FR' },
      { requestDomain: 'da-services.ch', owner: '', ownerCountry: '' },
      {
        requestDomain: 'doubleclick.net',
        owner: 'DoubleClick',
        ownerCountry: 'US',
      },
      { requestDomain: 'facebook.com', owner: 'Facebook', ownerCountry: 'US' },
      { requestDomain: 'facebook.net', owner: 'Facebook', ownerCountry: 'US' },
      { requestDomain: 'gbucket.ch', owner: '', ownerCountry: '' },
      {
        requestDomain: 'google-analytics.com',
        owner: 'Google Analytics',
        ownerCountry: 'US',
      },
      { requestDomain: 'google.ch', owner: 'Google', ownerCountry: 'US' },
      { requestDomain: 'google.com', owner: 'Google', ownerCountry: 'US' },
      {
        requestDomain: 'googlesyndication.com',
        owner: 'AdSense',
        ownerCountry: 'US',
      },
      {
        requestDomain: 'googletagmanager.com',
        owner: 'Google Tag Manager',
        ownerCountry: 'US',
      },
      {
        requestDomain: 'googletagservices.com',
        owner: 'Google Tag Manager',
        ownerCountry: 'US',
      },
      {
        requestDomain: 'jwplayer.com',
        owner: 'Longtail Ad Solutions',
        ownerCountry: 'US',
      },
      {
        requestDomain: 'jwpsrv.com',
        owner: 'Longtail Ad Solutions',
        ownerCountry: 'US',
      },
      { requestDomain: 'mookie1.com', owner: 'Xaxis', ownerCountry: 'US' },
      { requestDomain: 'onesignal.com', owner: '', ownerCountry: '' },
      { requestDomain: 'openx.net', owner: 'OpenX', ownerCountry: 'US' },
      { requestDomain: 'openxcdn.net', owner: '', ownerCountry: '' },
      { requestDomain: 'plista.com', owner: 'plista', ownerCountry: 'DE' },
      {
        requestDomain: 'quantserve.com',
        owner: 'Quantcast',
        ownerCountry: 'US',
      },
      {
        requestDomain: 'scorecardresearch.com',
        owner: 'ScorecardResearch',
        ownerCountry: 'US',
      },
      { requestDomain: 'ubimet.com', owner: '', ownerCountry: '' },
    ],
  },
  {
    name: 'zueritoday.ch',
    thirdParties: [
      { requestDomain: 'adnxs.com', owner: 'Xandr', ownerCountry: 'US' },
      { requestDomain: 'adnz.co', owner: '', ownerCountry: '' },
      { requestDomain: 'az-cdn.ch', owner: '', ownerCountry: '' },
      {
        requestDomain: 'chartbeat.com',
        owner: 'Chartbeat',
        ownerCountry: 'US',
      },
      {
        requestDomain: 'chartbeat.net',
        owner: 'Chartbeat',
        ownerCountry: 'US',
      },
      { requestDomain: 'coralproject.net', owner: '', ownerCountry: '' },
      {
        requestDomain: 'doubleclick.net',
        owner: 'DoubleClick',
        ownerCountry: 'US',
      },
      { requestDomain: 'facebook.com', owner: 'Facebook', ownerCountry: 'US' },
      { requestDomain: 'facebook.net', owner: 'Facebook', ownerCountry: 'US' },
      {
        requestDomain: 'google-analytics.com',
        owner: 'Google Analytics',
        ownerCountry: 'US',
      },
      { requestDomain: 'google.ch', owner: 'Google', ownerCountry: 'US' },
      { requestDomain: 'google.com', owner: 'Google', ownerCountry: 'US' },
      { requestDomain: 'googleoptimize.com', owner: '', ownerCountry: '' },
      {
        requestDomain: 'googletagmanager.com',
        owner: 'Google Tag Manager',
        ownerCountry: 'US',
      },
      {
        requestDomain: 'mailchimp.com',
        owner: 'Mailchimp',
        ownerCountry: 'US',
      },
      { requestDomain: 'onesignal.com', owner: '', ownerCountry: '' },
      {
        requestDomain: 'scorecardresearch.com',
        owner: 'ScorecardResearch',
        ownerCountry: 'US',
      },
      { requestDomain: 'telezueri.ch', owner: '', ownerCountry: '' },
    ],
  },
];
